### ISSUE TITLE
    maze_name_suffix = '' if cfg.width == cfg.height == 16 else f'_{cfg.width}x{cfg.height}' AttributeError: 'NoneType' object has no attribute 'width'

### ISSUE THREAD

**Issue by zhangzk123** [smearle/pathfinding-nca#2]
When running mazes.py，an error is reported:'NoneType' object has no attribute 'width'

**Comment by smearle** [comment]
I believe this results from the same issue outlined here: https://github.com/smearle/pathfinding-nca/issues/1#issuecomment-1289325605. Basically, run `python run_batch.py gen_new_data=True` to generate a new dataset of mazes.

**Comment by smearle** [comment]
Addressed in cba75e110118064d41850161c1efad650e05d8e5.
